### ISSUE TITLE
rofi window open on higher position than before

### ISSUE THREAD

**Issue by lonxwolx** [lr-tech/rofi-themes-collection#4] opened 2022-08-18 07:26 UTC
![rofi-screenshot](https://user-images.githubusercontent.com/63134947/185333380-948a2893-ca96-445c-b5fb-a159aa0eed75.png)

I can't think of anything that could have caused it, other than the system upgrade (that I did).

rofi version: 1.7.4(-1)
on Arch Linux

**Comment by lonxwolx** [comment] 2022-08-21 00:02
It is indeed caused by the upgrade (1.7.3 -> 1.7.4). After playing around, adding "anchor: north;" to window property fixes the position again (I don't know how though lol). Does not work on simple-tokyonight and windows11-* (works fine without it). Launchpad and the Nord (oneline and twolines) works just fine with or without it.

**Comment by ghost** [comment] 2022-10-25 23:04
had this same issue:

![image](https://user-images.githubusercontent.com/64506392/197898032-2be0dc8c-86e1-4933-9977-8f458715572e.png)

`anchor: north;` fixed it, as suggested!

![image](https://user-images.githubusercontent.com/64506392/197898200-93139296-d862-465d-9319-019c2a80fddd.png)

maybe some themes should be reworked to add `anchor: north;`?

**Comment by newmanls** [comment] 2022-11-26 23:09
Hi and sorry for the late answer!
This issue was caused by how rofi behaves with center-positioned windows. Before 1.7.4 it was needed a workaround, by using a 'y-offset' property to correctly center windows on certain themes, and that centering issue was fixed on the previously mentioned version.
Removing that property on those themes is enough now that rofi centers windows correctly. Now it should be working as expected.

**Closed as completed by newmanls** 2022-11-26 23:09 UTC
